
CREATE TABLE TG_USUARIO (
USUARI_N_CODIGO	INT,
USUARI_T_CORREO	VARCHAR(100),
USUARI_T_NOMBRE	VARCHAR(100),
USUARI_T_CONTRA	VARCHAR(50),
USUARI_N_GENERO	INT,
USUARI_T_FECNAC	VARCHAR(8),
USUARI_F_ACTIVO	INT	DEFAULT 1
)