
CREATE PROCEDURE [dbo].[PROC_TG_USUARIO_INSERTAR]
	@USUARI_T_CORREO		VARCHAR(100),
	@USUARI_T_NOMBRE		VARCHAR(100),
	@USUARI_T_CONTRA		VARCHAR(50),
	@USUARI_N_GENERO		INT,
	@USUARI_T_FECNAC		VARCHAR(8),
	@PAROUT_T_FILAFE		INT OUTPUT
AS
BEGIN TRY
	INSERT INTO TG_USUARIO 
	(
	USUARI_T_CORREO,
	USUARI_T_NOMBRE,
	USUARI_T_CONTRA,
	USUARI_N_GENERO,
	USUARI_T_FECNAC
	)
	VALUES
	(
	@USUARI_T_CORREO,
	@USUARI_T_NOMBRE,
	@USUARI_T_CONTRA,
	@USUARI_N_GENERO,
	@USUARI_T_FECNAC
	)

	SET @PAROUT_T_FILAFE = @@ROWCOUNT
END TRY
BEGIN CATCH
PRINT 'Error Number: ' + Convert(varchar(MAX),ERROR_NUMBER())
PRINT 'Error Severity: ' + Convert(varchar(MAX), ERROR_SEVERITY())
PRINT 'Error State: ' + Convert(varchar(MAX), ERROR_STATE())
PRINT 'Error Procedure: ' + Convert(varchar(MAX), ERROR_PROCEDURE())
PRINT 'Error Line: ' + Convert(varchar(MAX), ERROR_LINE())
PRINT 'Error Message: ' + Convert(varchar(MAX), ERROR_MESSAGE())
SET @PAROUT_T_FILAFE = 0
END CATCH
GO
--==============================================================================

CREATE PROCEDURE [dbo].[PROC_TG_TEST_LISTAR]
AS
BEGIN
	SELECT 
	TEST.TEST_N_CODIGO,
	TEST.TEST_T_DESCRI,
	SITUAC.SITUAC_N_CODIGO,
	SITUAC.SITUAC_T_DESCRI,
	SECCIO.SECCIO_N_CODIGO,
	SECCIO.SECCIO_T_DESCRI,
	RESPUE.RESPUE_N_CODIGO,
	RESPUE.RESPUE_T_DESCRI,
	SITRES.SITRES_N_CODIGO
	FROM		TG_TEST					TEST
	INNER JOIN	TG_SITUACION			SITUAC	ON	TEST.TEST_N_CODIGO		=	SITUAC.TEST_N_CODIGO	AND	SITUAC.SITUAC_F_ACTIVO	=	1
	INNER JOIN	TG_SITUACION_RESPUESTA	SITRES	ON	SITUAC.SITUAC_N_CODIGO	=	SITRES.SITUAC_N_CODIGO	AND	SITRES.SITRES_F_ACTIVO	=	1
	INNER JOIN	TG_RESPUESTA			RESPUE	ON	SITRES.RESPUE_N_CODIGO	=	RESPUE.RESPUE_N_CODIGO	AND	RESPUE.RESPUE_F_ACTIVO	=	1
	INNER JOIN	TG_SECCION				SECCIO	ON	RESPUE.SECCIO_N_CODIGO	=	SECCIO.SECCIO_N_CODIGO	AND	SECCIO.SECCIO_F_ACTIVO	=	1
	WHERE
	TEST.TEST_F_ACTIVO = 1
	ORDER BY SITRES.SITRES_N_CODIGO ASC
END
GO